services:
    app:
        image: mysql
        container_name: mysqlDB
        ports:
            - "3306:3306"
        expose:
            - 3306
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: qazse4321
            MYSQL_DATABASE: enterprise022
volumes:
    dbdata: