// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "REVAMPS-PHP-GO/internal/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// PortService is an autogenerated mock type for the PortService type
type PortService struct {
	mock.Mock
}

// ViewDataById provides a mock function with given fields: id
func (_m *PortService) ViewDataById(id string) (model.Account, error) {
	ret := _m.Called(id)

	var r0 model.Account
	if rf, ok := ret.Get(0).(func(string) model.Account); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPortService interface {
	mock.TestingT
	Cleanup(func())
}

// NewPortService creates a new instance of PortService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPortService(t mockConstructorTestingTNewPortService) *PortService {
	mock := &PortService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
