// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "REVAMPS-CMI-APPS/internal/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// PortRepo is an autogenerated mock type for the PortRepo type
type PortRepo struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *PortRepo) Get(id string) (model.Account, error) {
	ret := _m.Called(id)

	var r0 model.Account
	if rf, ok := ret.Get(0).(func(string) model.Account); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPortRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewPortRepo creates a new instance of PortRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPortRepo(t mockConstructorTestingTNewPortRepo) *PortRepo {
	mock := &PortRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
